name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous-Integration"]
    types:
      - completed

jobs:
  deploy-on-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Replace with your desired region

      - name: Connect to EC2 instance
        run: |
          ssh -i ${{ secrets.EC2_KEY_PAIR_PEM }} ubuntu@ec2-3-110-165-70.ap-south-1.compute.amazonaws.com

      - name: Pull Docker image
        run: sudo docker pull dharanshneema/heart-disease-detection-ml:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f heart-disease-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8501:8501 --name heart-disease-container dharanshneema/heart-disease-detection-ml
