name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous-Integration"]
    types:
      - completed

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: sudo docker pull dharanshneema/heart-disease-detection-ml:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f heart-disease-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8501:8501 --name heart-disease-container dharanshneema/heart-disease-detection-ml
